export const cedictIntroSet = [
  '% % [pa1] /percent (Tw)/',
  "21三體綜合症 21三体综合症 [er4 shi2 yi1 san1 ti3 zong1 he2 zheng4] /trisomy/Down's syndrome/",
  '3C 3C [san1 C] /abbr. for computers, communications, and consumer electronics/China Compulsory Certificate (CCC)/',
  'AA制 AA制 [A A zhi4] /to split the bill/to go Dutch/',
  'A咖 A咖 [A ka1] /class "A"/top grade/',
  'A片 A片 [A pian4] /adult movie/pornography/',
  'B型超聲 B型超声 [B xing2 chao1 sheng1] /type-B ultrasound/',
  'B超 B超 [B chao1] /type-B ultrasound/abbr. for B型超聲|B型超声[B xing2 chao1 sheng1]/',
  'C盤 C盘 [C pan2] /C drive or default startup drive (computing)/',
  'DNA鑒定 DNA鉴定 [D N A jian4 ding4] /DNA test/DNA testing/',
  'E仔 E仔 [e zai3] /MDMA (C11H15NO2)/',
  'G弦褲 G弦裤 [G xian2 ku4] /G-string/',
  'G點 G点 [G dian3] /Gräfenberg Spot/G-Spot/',
  'K仔 K仔 [K zai3] /ketamine (slang)/',
  'K他命 K他命 [k ta1 ming4] /ketamine (C13H16ClNO) (slang)/',
  'K房 K房 [K fang2] /(slang) KTV/KTV room/',
  'K書 K书 [K shu1] /to cram (Taiwan, from Taiwanese khè su 齧書, lit. to gnaw a book)/to study/see also 啃書|啃书[ken3 shu1]/',
  'K歌 K歌 [K ge1] /karaoke (slang)/',
  'K粉 K粉 [K fen3] /ketamine (slang)/',
  'M巾 M巾 [M jin1] /(coll.) menstrual pad/',
  'N檔 N档 [N dang4] /neutral (gear)/',
  'OK繃 OK绷 [OK beng1] /band-aid (Tw)/',
  'O型腿 O型腿 [O xing2 tui3] /bow legs/bow-leggedness/',
  'P圖 P图 [P tu2] /(Internet slang) to photoshop a picture/photoshopped picture/',
  'P檔 P档 [P dang4] /park (gear)/program mode (on a digital camera)/',
  'P民 P民 [P min2] /(slang) shitizen/commoner/hoi polloi/',
  'Q Q [Q] /cute (loanword)/(of food) having a pleasant chewiness (like mochi, tapioca pearls, taro balls etc - foods with a springy or gel-like mouthfeel)/',
  'T字帳 T字帐 [T zi4 zhang4] /T-account (accounting)/',
  'T字褲 T字裤 [T zi4 ku4] /thong (underwear)/',
  'T恤 T恤 [T xu4] /T-shirt/',
  'T裇 T裇 [T xu1] /T-shirt/',
  'USB手指 USB手指 [U S B shou3 zhi3] /USB flash drive/see also 閃存盤|闪存盘[shan3 cun2 pan2]/',
  'USB記憶棒 USB记忆棒 [U S B ji4 yi4 bang4] /USB flash drive/see also 閃存盤|闪存盘[shan3 cun2 pan2]/',
  'U形轉彎 U形转弯 [U xing2 zhuan3 wan1] /U-turn/',
  'U盤 U盘 [U pan2] /USB flash drive/see also 閃存盤|闪存盘[shan3 cun2 pan2]/',
  'V溝 V沟 [V gou1] /low neckline that reveals the cleavage/décolleté/gully/',
  'X光 X光 [X guang1] /X-ray/',
  '○ ○ [ling2] /character used in Taiwan as a substitute for a real name (like "X" in English)/variant of 〇[ling2]/',
  '〇 〇 [ling2] /zero/',
  '〡 〡 [yi1] /numeral 1 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/',
  '〢 〢 [er4] /numeral 2 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/',
  '〣 〣 [san1] /numeral 3 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/',
  '〤 〤 [si4] /numeral 4 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/',
  '〥 〥 [wu3] /numeral 5 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/',
  '〦 〦 [liu4] /numeral 6 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/',
  '〧 〧 [qi1] /numeral 7 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/',
  '〨 〨 [ba1] /numeral 8 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/',
  '〩 〩 [jiu3] /numeral 9 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/',
  '㐄 㐄 [kua4] /component in Chinese characters, mirror image of 夂[zhi3]/',
  '㐅 㐅 [wu3] /archaic variant of 五[wu3]/',
  '㐆 㐆 [yin3] /component in Chinese character 殷[yin1]/',
  '㐌 㐌 [ta1] /variant of 它[ta1]/',
  '㐖 㐖 [Ye4] /see 㐖毒[Ye4 du2]/',
  '㐖毒 㐖毒 [Ye4 du2] /India (archaic)/',
];
